import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
import {pathToFileURL} from 'node:url';
const sqlite=new DatabaseSync(':memory:');
for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));
const DB={prepare(sql){let args=[];return {bind(...values){args=values;return this;},async first(column){const row=sqlite.prepare(sql).get(...args);return column?row?.[column]??null:row??null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}};},async batch(items){sqlite.exec('BEGIN');try{const result=await Promise.all(items.map(i=>i.run()));sqlite.exec('COMMIT');return result;}catch(error){sqlite.exec('ROLLBACK');throw error;}}};
const objects=new Map();
globalThis.__env={DB,BUCKET:{async get(key){const bytes=objects.get(key);return bytes?{body:new ReadableStream({start(c){c.enqueue(bytes);c.close();}})}:null;}},ENVIRONMENT:'production',STAFF_USER_EMAILS:'staff@example.org',WHATSAPP_ACCESS_TOKEN:'test',WHATSAPP_PHONE_NUMBER_ID:'test',WHATSAPP_GRAPH_VERSION:'v24.0'};
const sends=[];globalThis.fetch=async (_url,options)=>{sends.push(JSON.parse(options.body));return Response.json({messages:[{id:'test-'+sends.length}]});};
const modules=new Map();const envUrl='data:text/javascript;base64,'+Buffer.from('export const env=globalThis.__env').toString('base64');
async function load(name){if(modules.has(name))return modules.get(name);let code=ts.transpileModule(fs.readFileSync('lib/civicflow/'+name+'.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;code=code.replace(/import\("\.\/notifications"\)/g,'globalThis.__notifications()');for(const match of [...code.matchAll(/from ["']\.\/(.*?)["']/g)])code=code.replaceAll(match[0],`from ${JSON.stringify(await load(match[1]))}`);code=code.replaceAll('"cloudflare:workers"',JSON.stringify(envUrl)).replaceAll("'cloudflare:workers'",JSON.stringify(envUrl)).replaceAll('"fflate"',JSON.stringify(pathToFileURL(process.cwd()+'/node_modules/fflate/esm/index.mjs').href)).replaceAll("'fflate'",JSON.stringify(pathToFileURL(process.cwd()+'/node_modules/fflate/esm/index.mjs').href));const url='data:text/javascript;base64,'+Buffer.from(code).toString('base64');modules.set(name,url);return url;}
const repo=await import(await load('repository'));const notifications=await import(await load('notifications'));globalThis.__notifications=async()=>notifications;
const review=await import(await load('review'));const vetting=await import(await load('vetting'));const workflow=await import(await load('workflow'));const staff=await import(await load('staff-auth'));
await assert.rejects(async()=>staff.requireStaff(new Request('https://test')),e=>e.status===401);
await repo.createCase({id:'case',reference:'CF-TEST',channel:'WHATSAPP',language:'af',applicantName:'Test resident'});
await repo.createSession({id:'session',channelType:'WHATSAPP',channelIdentifier:'27820000000'});
await repo.saveSession('session',{workflowStep:'MAIN_MENU',language:'af',authLevel:1,caseId:'case',context:{language:'af',resumeStep:'SUBMITTED'}});
await repo.addMessage({sessionId:'session',caseId:'case',direction:'INBOUND',providerMessageId:'inbound',body:'test'});
await repo.addRequirement({id:'requirement',caseId:'case',code:'APPLICANT_ID',label:'Identity document'});
sqlite.prepare("INSERT INTO documents (id,case_id,requirement_id,object_key,original_filename,mime_type,file_size,content_hash,status,source_channel,created_at) VALUES ('doc','case','requirement','private-key','id.pdf','application/pdf',3,'hash','UPLOADED_PENDING_REVIEW','WHATSAPP',?)").run(new Date().toISOString());objects.set('private-key',new Uint8Array([1,2,3]));
await repo.updateCase('case',{state:'DOCUMENTS_UNDER_REVIEW',submitted:true});
await assert.rejects(()=>vetting.handoff('case','staff',{action:'PREPARE',target:'MANUAL'}),e=>e.status===400);
await assert.rejects(()=>review.reviewDocument('doc','staff',{pass:true,checked:[]}),e=>e.status===400);
await review.reviewDocument('doc','staff',{pass:false,reason:'The name is blurred'});
assert.equal(sqlite.prepare("SELECT current_state FROM cases WHERE id='case'").get().current_state,'DOCUMENT_REUPLOAD_REQUIRED');
const checks=review.checklist('APPLICANT_ID');assert(!checks.some(c=>/validity|authenticity|checksum/i.test(c)));
await review.reviewDocument('doc','staff',{pass:true,checked:checks});
assert.equal(sqlite.prepare("SELECT current_state FROM cases WHERE id='case'").get().current_state,'READY_FOR_VETTING');
const packet=await vetting.handoff('case','staff',{action:'PREPARE',target:'INDYREACH'});
assert.equal(sqlite.prepare('SELECT status FROM vetting_handoffs WHERE id=?').get(packet.id).status,'PREPARED');
await assert.rejects(()=>vetting.handoff('case','staff',{action:'OUTCOME',handoffId:packet.id,outcome:'APPROVED',reason:'External result'}),e=>e.status===400);
const archive=await vetting.handoffArchive('case',packet.id);const {unzipSync}=await import('fflate');const files=unzipSync(new Uint8Array(await archive.arrayBuffer()));assert.equal(files['documents/doc-id.pdf'].length,3);assert(!new TextDecoder().decode(files['application.json']).includes('private-key'));
await vetting.handoff('case','staff',{action:'SENT',handoffId:packet.id,externalReference:'IR-123'});
await assert.rejects(()=>review.reviewDocument('doc','staff',{pass:true,checked:checks}),e=>e.status===400);
await vetting.handoff('case','staff',{action:'OUTCOME',handoffId:packet.id,outcome:'DECLINED',reason:'Decision returned by reviewer: IR-123'});
assert.equal(sqlite.prepare("SELECT current_state FROM cases WHERE id='case'").get().current_state,'OUTCOME_DECLINED');
assert(sqlite.prepare('SELECT count(*) AS n FROM whatsapp_notifications').get().n>=6);
assert(sends.some(s=>JSON.stringify(s).includes('Afgekeur')));
const input={sessionId:'session',channelType:'WHATSAPP',channelIdentifier:'27820000000'};
let reply=await workflow.processChat({...input,action:'MENU_HOME'});assert(reply.choices.some(c=>c.id==='MENU_LANGUAGE'));
reply=await workflow.processChat({...input,action:'MENU_LANGUAGE'});assert.equal(reply.step,'LANGUAGE_CHANGE');
reply=await workflow.processChat({...input,action:'LANG_EN'});assert.equal(reply.language,'en');assert.equal(reply.step,'MAIN_MENU');assert(reply.choices.some(c=>c.id==='MENU_CONTINUE'));
assert.equal(sqlite.prepare("SELECT current_state FROM cases WHERE id='case'").get().current_state,'OUTCOME_DECLINED');
const before=sqlite.prepare('SELECT count(*) AS n FROM whatsapp_notifications').get().n;
sqlite.prepare("UPDATE messages SET created_at='2000-01-01' WHERE direction='INBOUND'").run();
await notifications.queueRecommendation('case','INFORMATION_REQUIRED');await notifications.queueRecommendation('case','VETTING_IN_PROGRESS');
assert.equal(sqlite.prepare('SELECT count(*) AS n FROM whatsapp_notifications').get().n,before+2);
assert.equal(sqlite.prepare("SELECT count(*) AS n FROM whatsapp_notifications WHERE status='WAITING_FOR_REPLY'").get().n,2);
console.log('PASS: surface checks, handoff gate, ZIP files, external outcome provenance, every status retained, staff gate and Afrikaans→English menu');
