'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export function DocumentReview({document,checks,reload}:{document:any;checks:string[];reload:()=>Promise<void>}) {
 const [checked,setChecked]=useState<string[]>([]);const [reason,setReason]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function save(pass:boolean){setBusy(true);try{const res=await fetch(`/api/documents/${document.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({pass,checked,reason})});const data=await res.json() as {error?:string};if(!res.ok)setMessage(data.error || "Unable to save");else{setMessage('Basic review saved');await reload();}}catch{setMessage('Unable to save review');}finally{setBusy(false);}}
 return <div className="mt-3 space-y-2 text-sm"><p className="font-semibold">Basic completeness and legibility only</p>{checks.map(check=><label key={check} className="flex items-start gap-2"><input type="checkbox" checked={checked.includes(check)} onChange={e=>setChecked(e.target.checked?[...checked,check]:checked.filter(c=>c!==check))}/>{check}</label>)}<Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Details the resident must upload again"/><div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy || checked.length!==checks.length} onClick={()=>void save(true)}>Basic check passed</Button><Button size="sm" variant="outline" disabled={busy || !reason.trim()} onClick={()=>void save(false)}>Request clearer upload</Button></div><p role="status">{message}</p></div>;
}
export function VettingControls({caseId,entries,reload}:{caseId:string;entries:any[];reload:()=>Promise<void>}) {
 const [target,setTarget]=useState('MANUAL');const [reference,setReference]=useState('');const [outcome,setOutcome]=useState('UNDER_REVIEW');const [reason,setReason]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function run(action:string,handoffId?:string){setBusy(true);try{const res=await fetch(`/api/cases/${caseId}/handoff`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,handoffId,target,externalReference:reference,outcome,reason})});const data=await res.json() as {error?:string};setMessage(res.ok?'Handoff updated':data.error || 'Unable to update');if(res.ok)await reload();}catch{setMessage('Unable to update handoff');}finally{setBusy(false);}}
 return <div className="rounded-xl border p-4 space-y-3"><h3 className="font-bold">External vetting / authorised manual review</h3><p className="text-sm text-slate-500">Download and forward the packet to the reviewer. Record their returned result below. Direct IndyReach integration awaits its API details.</p><select className="border rounded p-2" value={target} onChange={e=>setTarget(e.target.value)}><option value="MANUAL">Authorised manual reviewer</option><option value="INDYREACH">IndyReach</option><option value="THIRD_PARTY">Other third-party system</option></select><Button size="sm" disabled={busy} onClick={()=>void run('PREPARE')}>Prepare handoff bundle</Button>{entries.map(entry=><div key={entry.id} className="border rounded p-3 space-y-2"><p>{entry.target} · {entry.status} · {entry.external_reference || 'Not yet forwarded'}</p><a className="underline" href={`/api/cases/${caseId}/handoff?handoffId=${entry.id}`}>Download documents and application ZIP</a>{entry.status==='PREPARED'&&<><Input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Receiving reviewer’s reference"/><Button size="sm" disabled={busy || !reference.trim()} onClick={()=>void run('SENT',entry.id)}>Confirm actually forwarded</Button></>}{entry.status==='SENT'&&<><p className="font-semibold">Record result returned by the reviewer</p><select className="border rounded p-2" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="UNDER_REVIEW">Under review</option><option value="APPROVED">Approved</option><option value="DECLINED">Declined</option><option value="INFORMATION_REQUIRED">Further information required</option></select><Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reviewer’s reason or evidence reference"/><Button size="sm" disabled={busy || !reason.trim()} onClick={()=>void run('OUTCOME',entry.id)}>Record returned outcome</Button></>}</div>)}<p role="status" className="text-sm">{message}</p></div>;
}
